version: '2'

services:
  postgres_db:
    build: postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    build: mysite
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - "postgres_db"
